"""innit migration

Revision ID: 304e8603a3bb
Revises: 
Create Date: 2025-09-15 10:36:20.528624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '304e8603a3bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casos',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único interno del caso'),
    sa.Column('numero_caso', sa.Integer(), nullable=False, comment='Número consecutivo del caso por tipo y año'),
    sa.Column('anio', sa.Integer(), nullable=False, comment='Año del caso para optimizar consultas'),
    sa.Column('tipo', sa.Enum('PETICION', 'QUEJA', 'RECLAMO', 'SUGERENCIA', 'DENUNCIA', name='tipocaso'), nullable=False, comment='Tipo de caso PQRSD'),
    sa.Column('asunto', sa.String(length=200), nullable=False, comment='Título o asunto del caso'),
    sa.Column('descripcion', sa.Text(), nullable=False, comment='Descripción detallada del caso'),
    sa.Column('nombre_solicitante', sa.String(length=100), nullable=False, comment='Nombre completo del solicitante'),
    sa.Column('email_solicitante', sa.String(length=255), nullable=False, comment='Email del solicitante'),
    sa.Column('telefono_solicitante', sa.String(length=15), nullable=True, comment='Teléfono de contacto del solicitante'),
    sa.Column('estado', sa.Enum('RECIBIDO', 'EN_PROCESO', 'RESUELTO', 'CERRADO', name='estadocaso'), nullable=False, comment='Estado actual del caso'),
    sa.Column('respuesta', sa.Text(), nullable=True, comment='Respuesta oficial al caso'),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación del caso'),
    sa.Column('fecha_actualizacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de la última actualización'),
    sa.PrimaryKeyConstraint('id'),
    comment='Tabla principal para almacenar casos PQRSD del sistema. Optimizada para PostgreSQL con índices estratégicos para consultas frecuentes.'
    )
    op.create_index('idx_caso_anio', 'casos', ['anio'], unique=False)
    op.create_index('idx_caso_email_estado', 'casos', ['email_solicitante', 'estado'], unique=False)
    op.create_index('idx_caso_fecha_desc', 'casos', ['fecha_creacion'], unique=False)
    op.create_index('idx_caso_fecha_estado', 'casos', ['fecha_creacion', 'estado'], unique=False)
    op.create_index('idx_caso_tipo_anio_numero', 'casos', ['tipo', 'anio', 'numero_caso'], unique=True)
    op.create_index('idx_caso_tipo_estado', 'casos', ['tipo', 'estado'], unique=False)
    op.create_index(op.f('ix_casos_anio'), 'casos', ['anio'], unique=False)
    op.create_index(op.f('ix_casos_email_solicitante'), 'casos', ['email_solicitante'], unique=False)
    op.create_index(op.f('ix_casos_estado'), 'casos', ['estado'], unique=False)
    op.create_index(op.f('ix_casos_id'), 'casos', ['id'], unique=False)
    op.create_index(op.f('ix_casos_numero_caso'), 'casos', ['numero_caso'], unique=False)
    op.create_index(op.f('ix_casos_tipo'), 'casos', ['tipo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_casos_tipo'), table_name='casos')
    op.drop_index(op.f('ix_casos_numero_caso'), table_name='casos')
    op.drop_index(op.f('ix_casos_id'), table_name='casos')
    op.drop_index(op.f('ix_casos_estado'), table_name='casos')
    op.drop_index(op.f('ix_casos_email_solicitante'), table_name='casos')
    op.drop_index(op.f('ix_casos_anio'), table_name='casos')
    op.drop_index('idx_caso_tipo_estado', table_name='casos')
    op.drop_index('idx_caso_tipo_anio_numero', table_name='casos')
    op.drop_index('idx_caso_fecha_estado', table_name='casos')
    op.drop_index('idx_caso_fecha_desc', table_name='casos')
    op.drop_index('idx_caso_email_estado', table_name='casos')
    op.drop_index('idx_caso_anio', table_name='casos')
    op.drop_table('casos')
    # ### end Alembic commands ###
