"""reorganizar_campos_tabla_casos

Revision ID: 7bf2bef14c97
Revises: e78cd4d5ef2d
Create Date: 2025-09-22 15:29:11.942956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf2bef14c97'
down_revision: Union[str, Sequence[str], None] = 'e78cd4d5ef2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('casos', 'numero_caso_completo',
               existing_type=sa.VARCHAR(length=20),
               comment='Número de caso formateado para búsquedas rápidas (ej: PET-2025-0004)',
               existing_nullable=True)
    op.drop_index(op.f('idx_caso_numero_completo'), table_name='casos')
    op.create_index(op.f('ix_casos_numero_caso_completo'), 'casos', ['numero_caso_completo'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_casos_numero_caso_completo'), table_name='casos')
    op.create_index(op.f('idx_caso_numero_completo'), 'casos', ['numero_caso_completo'], unique=True)
    op.alter_column('casos', 'numero_caso_completo',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Número de caso formateado para búsquedas rápidas (ej: PET-2025-0004)',
               existing_nullable=True)
    # ### end Alembic commands ###
